"""PulseFlow contracts: Decisions.

Defines the decision objects issued by Shrikar's adaptive scheduler
and enforced by Aradhya's pipeline execution engine.
"""

import time
from typing import Optional
from pydantic import BaseModel, Field, model_validator

from contracts.priorities import Priority
from contracts.actions import Action


class InvalidDecisionError(ValueError):
    """Raised when an illegal processing decision is attempted (e.g., shedding CRITICAL events)."""
    pass


class ProcessingDecision(BaseModel):
    """Per-lane processing decision generated by the adaptive scheduler."""
    priority: Priority = Field(
        ...,
        description="Target priority lane",
    )
    action: Action = Field(
        ...,
        description="Action to execute on this lane (STREAM, BATCH, DEFER, SAMPLE, SHED)",
    )
    sample_rate: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Fraction of events to process when action=SAMPLE (0.0 to 1.0)",
    )
    batch_size: int = Field(
        default=50,
        ge=1,
        description="Micro-batch size when action=BATCH",
    )
    batch_timeout_ms: float = Field(
        default=100.0,
        ge=0.0,
        description="Maximum wait time in ms before processing a partial micro-batch",
    )
    target_workers: Optional[int] = Field(
        default=None,
        ge=0,
        description="Target number of workers allocated to this lane",
    )

    @model_validator(mode="after")
    def validate_safety_rules(self) -> "ProcessingDecision":
        """Enforce strict invariant: CRITICAL events must never be shed or sampled."""
        if self.priority == Priority.CRITICAL:
            if self.action == Action.SHED:
                raise InvalidDecisionError("CRITICAL priority lane cannot have action=SHED. Critical events must never be shed!")
            if self.action == Action.SAMPLE and self.sample_rate < 1.0:
                raise InvalidDecisionError("CRITICAL priority lane cannot be sampled below 100%. Critical events must never be dropped!")
        return self


def validate_decision_for_event(event_priority: Priority, decision: ProcessingDecision) -> None:
    """Runtime safety guard protecting critical events from illegal degradation actions."""
    if event_priority == Priority.CRITICAL:
        if decision.action == Action.SHED:
            raise InvalidDecisionError("CRITICAL events must never be shed!")
        if decision.action == Action.SAMPLE and decision.sample_rate < 1.0:
            raise InvalidDecisionError("CRITICAL events must never be sampled below 100%!")


class SystemDecision(BaseModel):
    """Holistic system decision containing lane policies, pressure metric, and worker distribution."""
    timestamp: float = Field(
        default_factory=time.time,
        description="Decision generation timestamp",
    )
    pressure: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Current system pressure index from 0.0 (calm) to 1.0 (overload)",
    )
    lane_decisions: dict[Priority, ProcessingDecision] = Field(
        default_factory=dict,
        description="Decision per priority lane",
    )
    worker_allocation: dict[Priority, int] = Field(
        default_factory=dict,
        description="Allocated worker counts per priority lane",
    )

    @model_validator(mode="after")
    def validate_allocation(self) -> "SystemDecision":
        """Validate that all worker allocations are non-negative."""
        for lane, count in self.worker_allocation.items():
            if count < 0:
                raise InvalidDecisionError(f"Worker allocation for {lane} cannot be negative: {count}")
        return self

    def get_lane_decision(self, priority: Priority) -> Optional[ProcessingDecision]:
        """Convenience method to retrieve decision for a specific priority lane."""
        return self.lane_decisions.get(priority)

    def get_workers_for_lane(self, priority: Priority, default: int = 0) -> int:
        """Convenience method to get allocated workers for a lane."""
        return self.worker_allocation.get(priority, default)
