"""PulseFlow module: event_factory.

Generates synthetic workload events for TechPulse.
"""

import random
from typing import Any, List, Optional

from contracts.events import Event, EventBatch


class EventFactory:
    """Factory for generating synthetic events for PulseFlow benchmarking and testing."""

    STANDARD_TYPES = [
        "ORDER", "PAYMENT", "CART_ADD", "INVENTORY_UPDATE", 
        "CLICK", "PAGE_VIEW", "LOG"
    ]

    def __init__(self, seed: Optional[int] = None):
        """Initialize the event factory.
        
        Args:
            seed: Optional integer seed for deterministic event generation.
        """
        self.rng = random.Random(seed)

    def _generate_payload(self, event_type: str) -> dict[str, Any]:
        """Generate a realistic synthetic payload based on the event type."""
        if event_type == "ORDER":
            return {
                "user_id": f"usr_{self.rng.randint(1, 10000)}",
                "order_id": f"ord_{self.rng.randint(1000, 999999)}",
                "amount": round(self.rng.uniform(10.0, 500.0), 2),
                "currency": "USD"
            }
        elif event_type == "PAYMENT":
            return {
                "user_id": f"usr_{self.rng.randint(1, 10000)}",
                "payment_id": f"pay_{self.rng.randint(1000, 999999)}",
                "amount": round(self.rng.uniform(10.0, 500.0), 2),
                "currency": "USD",
                "payment_method": self.rng.choice(["CREDIT_CARD", "PAYPAL", "WALLET", "BANK_TRANSFER"])
            }
        elif event_type == "CART_ADD":
            return {
                "user_id": f"usr_{self.rng.randint(1, 10000)}",
                "product_id": f"prod_{self.rng.randint(1, 5000)}",
                "quantity": self.rng.randint(1, 5)
            }
        elif event_type == "INVENTORY_UPDATE":
            return {
                "product_id": f"prod_{self.rng.randint(1, 5000)}",
                "quantity": self.rng.randint(-50, 50),
                "warehouse_id": f"wh_{self.rng.randint(1, 10)}"
            }
        elif event_type == "CLICK":
            return {
                "user_id": f"usr_{self.rng.randint(1, 10000)}",
                "page": self.rng.choice(["/home", "/product", "/checkout", "/search", "/category"]),
                "element": self.rng.choice(["add_to_cart_btn", "checkout_btn", "search_bar", "banner_ad", "product_link"])
            }
        elif event_type == "PAGE_VIEW":
            return {
                "user_id": f"usr_{self.rng.randint(1, 10000)}",
                "page": self.rng.choice(["/home", "/product", "/checkout", "/search", "/category"])
            }
        elif event_type == "LOG":
            return {
                "service": self.rng.choice(["auth-service", "cart-service", "inventory-service", "payment-gateway", "frontend"]),
                "level": self.rng.choices(["INFO", "WARN", "ERROR", "DEBUG"], weights=[0.7, 0.15, 0.05, 0.1])[0],
                "message": "Synthetic log message generated by TechPulse."
            }
        else:
            return {"data": "unknown event type", "value": self.rng.random()}

    def create_event(self, event_type: Optional[str] = None) -> Event:
        """Create a single Event.
        
        If event_type is not provided, a random standard type is chosen.
        """
        if event_type is None:
            event_type = self.rng.choice(self.STANDARD_TYPES)
            
        payload = self._generate_payload(event_type)
        
        event = Event(
            event_type=event_type,
            payload=payload
        )
        
        # Resolve priority using the shared logic in Event
        event.ensure_priority()
        return event
        
    def create_events(self, count: int, event_types: Optional[List[str]] = None) -> EventBatch:
        """Create a batch of Events.
        
        Args:
            count: Number of events to generate.
            event_types: Optional subset of types to choose from. If None, uses all standard types.
        """
        events = []
        for _ in range(count):
            et = self.rng.choice(event_types) if event_types else self.rng.choice(self.STANDARD_TYPES)
            events.append(self.create_event(et))
            
        return EventBatch(events=events)
